
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:/test?serverTimezone=Asia/Seoul
    username: root
    password: gustjr0227
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        show-sql: true
        format-sql: true
  sql.init.mode: always
logging.level:
  org.hibernate.SQL: debug